# Generated by Django 4.2.2 on 2023-06-26 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tbl_shops',
            table='tbl_shops',
        ),
    ]
